name: Building New Kernel

on: [push]

env:
  GIT_SECRETB: ${{ secrets.GIT_SECRETB }}
  GIT_SECRET: ${{ secrets.GIT_SECRET }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}

jobs:
  build-begonia-r-oss-stock-main:

    runs-on: ubuntu-latest

    container:
      image: zycromerz/kerneldocker:v3

    steps:
    - uses: actions/checkout@v2
    - name: Compile Kernel
      run: |
        chmod +x maing.sh
        bash maing.sh 'begonia-r-oss-stock-main'

